name: bd_l10n
description: Tools that help manage localization for a dart/flutter application.
version: 1.2.0
homepage: https://github.com/bitsydarel/bd_l10n
repository: https://github.com/bitsydarel/bd_l10n
issue_tracker: https://github.com/bitsydarel/bd_l10n/issues

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  # provide ability to parse command line arguments.
  args: ^2.1.1
  # provider builder capabilities.
  build: ^2.0.3
  build_config: ^1.0.0
  io: ^1.0.3
  # Allow to generate json conversion from annotation.
  json_annotation: ^4.1.0
  # Provide metadata annotation that help make code intention more clear.
  meta: ^1.7.0
  # provide utility method to work with path
  path: ^1.8.0
  # Provide classes to implement file/directory watching.
  watcher: ^1.0.0
  # provide ability to parse yaml file.
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.6
  # project code style.
  flutter_code_style: ^2.1.0
  # create json conversion utility.
  json_serializable: ^5.0.0
  test: ^1.17.10

executables:
  bd_l10n: